#!/usr/bin/env -S sh -eu
if [ -d $TARGET ]; then
    for TIMESTAMP in $(find $TARGET/archive/all -maxdepth 1 -mindepth 1 -type d -exec basename {} \;); do
        SHA1SUM_GZ="$TARGET/archive/all/$TIMESTAMP/meta/sha1sum.gz"
        cat $SHA1SUM_GZ | eval $COMPRESSION_DECOMPRESS | eval $CHECKSUM_CHECK
    done
fi
