#!/usr/bin/env -S sh -eu
SOURCE=$1
TARGET=$2
TIMESTAMP=$3
mkdir -p $TARGET/archive/all/$TIMESTAMP $TARGET/latest
OPTS='-ac'
if [ -L $TARGET/latest/all ]; then
    OPTS="$OPTS --link-dest $(readlink -f $TARGET/latest/all)"
fi
if [ ! -z "$(ls $SOURCE)" ]; then
    rsync $OPTS $SOURCE/ $TARGET/archive/all/$TIMESTAMP
fi
rm -f $TARGET/latest/all
ln -s ../archive/all/$TIMESTAMP $TARGET/latest/all
