#!/usr/bin/env -S sh -eu
SOURCE=$1
TARGET=$2
CHECKSUM_CALCULATE="${CHECKSUM_CALCULATE:-sha1sum}"
mkdir -p $TARGET/archive/all/$TIMESTAMP/data $TARGET/archive/all/$TIMESTAMP/meta $TARGET/latest
OPTS='-ac'
if [ -L $TARGET/latest/all ]; then
    OPTS="$OPTS --link-dest $(readlink -f $TARGET/latest/all)/data"
fi
if [ ! -z "$(ls $SOURCE)" ]; then
    rsync $OPTS $SOURCE/ $TARGET/archive/all/$TIMESTAMP/data
    (cd $TARGET/archive/all/$TIMESTAMP/data; find . -type f -printf '%P\0' | xargs -0 $CHECKSUM_CALCULATE | eval $COMPRESS_PIPE > $TARGET/archive/all/$TIMESTAMP/meta/sha1sum.gz)
fi
rm -f $TARGET/latest/all
ln -s ../archive/all/$TIMESTAMP $TARGET/latest/all
